"""posts table

Revision ID: eaf7b13eba2b
Revises: 
Create Date: 2022-06-01 15:02:58.800480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf7b13eba2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_blogpost_date_posted'), ['date_posted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogpost_date_posted'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
